# Generated by Django 3.2.9 on 2021-12-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_winner_listing_temp_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_starting_bid',
            field=models.BooleanField(default=False),
        ),
    ]
