# Generated by Django 3.2.9 on 2021-12-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_is_starting_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_starting_bid',
        ),
    ]
