# Generated by Django 4.1.2 on 2022-10-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('isOpen', models.BooleanField()),
                ('allotedTime', models.IntegerField()),
            ],
        ),
    ]
