# Generated by Django 4.1.2 on 2022-10-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
